apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: NODE_INSTANCE_ROLE
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
        # next line allows deployments (jenkins)
        - system:masters
    - rolearn: arn:aws:iam::302724950430:user/admin
      username: admin
      groups:
        - system:masters
    
